name: noyce_joyce_nixie
description: Noyce Joyce Nixie is an application written in flutter for controlling nixie products from Noyce Joyce.
publish_to: 'none'
version: 1.0.6+7

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.0.3
  nordic_dfu: ^5.2.1
  permission_handler: ^10.2.0
  easy_localization: ^3.0.1
  url_launcher: ^6.1.8
  provider: ^6.0.5
  package_info_plus: ^3.0.2
  flutter_datetime_picker: 
    git:
      url: git@github.com:michalvalkoun/flutter_datetime_picker.git
      ref: master
  signal_strength_indicator: ^0.4.1
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.17
  meta: ^1.8.0
  intl: ^0.17.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  rename: ^2.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
     - family: Abraham
       fonts:
         - asset: assets/Abraham.otf